---
route:
  fields:
    input:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    output:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

save_preset:
  fields:
    preset:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

recall_preset:
  fields:
    preset:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

cec_command:
  fields:
    target:
      required: true
      selector:
        select:
          options:
            - input
            - output
    port:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    command:
      required: true
      selector:
        select:
          options:
            - play
            - pause
            - stop
            - standby
            - power_on
            - volume_up
            - volume_down
            - volume_mute

get_status:
  fields: {}
