route:
  fields:
    input:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    output:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

save_preset:
  fields:
    preset:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

recall_preset:
  fields:
    preset:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

clear_preset:
  fields:
    preset:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

set_preset_name:
  fields:
    preset:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    name:
      required: true
      selector:
        text: {}

cec_command:
  fields:
    side:
      required: true
      selector:
        select:
          options:
            - input
            - output
    port:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    command:
      required: true
      selector:
        select:
          options:
            - enter
            - left
            - right
            - up
            - down
            - menu
            - play
            - pause
            - stop
            - prev_track
            - next_track
            - rewind
            - fast_forward
            - loop
            - power_on
            - power_off
            - mute
            - volume_up
            - volume_down

set_power:
  fields:
    "on":
      required: false
      default: true
      selector:
        boolean: {}

set_mute:
  fields:
    output:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    muted:
      required: false
      default: true
      selector:
        boolean: {}

refresh:
  fields: {}
